on:
  - pull_request
  - push

name: backwards compatibility

jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@master
    with:
      extensions: uopz
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
